import React from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import './CompanyExpenses.css';
import logo from '../../assets/ofiiceLogo.webp'; 

const expensesData = [
  {
    date: '2025-06-01',
    type: 'Purchase',
    description: 'Office Chairs',
    quantity: 10,
    item: 'Ergonomic Chair',
    client: 'Nilkamal Ltd',
    status: 'Paid',
    expiryDate: '2027-06-01',
    amount: 25000,
    gst: 4500,
    total: 29500,
  },
  {
    date: '2025-06-05',
    type: 'Service',
    description: 'AC Maintenance',
    quantity: 1,
    item: 'Maintenance Service',
    client: 'CoolTech Services',
    status: 'Pending',
    expiryDate: 'N/A',
    amount: 5000,
    gst: 900,
    total: 5900,
  },
  {
    date: '2025-06-10',
    type: 'Subscription',
    description: 'Cloud Hosting',
    quantity: 12,
    item: 'Monthly Hosting',
    client: 'AWS',
    status: 'Paid',
    expiryDate: '2026-06-10',
    amount: 12000,
    gst: 2160,
    total: 14160,
  }
];

// Company Header
 const addCompanyHeader = (doc) => {
  const logoWidth = 40;
  const logoHeight = 20;
  const logoX = 14;
  const logoY = 10;

  doc.addImage(logo, 'PNG', logoX, logoY, logoWidth, logoHeight);

  const textX = logoX + logoWidth + 10;
  const textYStart = logoY + 5;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("SORIM TECHNOLOGIES", textX, textYStart);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("4, Velayutham St, Puzhuthivakkam,", textX, textYStart + 7);
  doc.text("Madipakkam, Chennai, Tamil Nadu 600091", textX, textYStart + 12);
};

 const CompanyExpenses = () => {
  const exportPDF = () => {
  const doc = new jsPDF();
  addCompanyHeader(doc);

  const today = new Date();
  const formattedDate = today.toLocaleDateString();
  const day = today.toLocaleDateString(undefined, { weekday: 'long' });

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Company Expense Report", 105, 45, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Date: ${formattedDate}`, 14, 55);
  doc.text(`Day: ${day}`, 160, 55);

  const totalSum = expensesData.reduce((sum, e) => sum + (e.total || 0), 0);

  autoTable(doc, {
    startY: 65,
    head: [[
      "Date", "Type", "Description", "Qty", "Item", "Client",
      "Status", "Expiry", "Amount", "GST", "Total"
    ]],
    body: expensesData.map(exp => [
      exp.date,
      exp.type,
      exp.description,
      exp.quantity,
      exp.item,
      exp.client,
      exp.status,
      exp.expiryDate,
      `INR ${exp.amount.toLocaleString()}`,
      `INR ${exp.gst.toLocaleString()}`,
      `INR ${exp.total.toLocaleString()}`
    ]),
    styles: {
      fontSize: 9,
      cellPadding: 2,
      overflow: 'visible',
      halign: 'left',
      valign: 'middle'
    },
    columnStyles: {
      0: { cellWidth: 22 }, // Date
      1: { cellWidth: 20 }, // Type
      2: { cellWidth: 30 }, // Description
      3: { cellWidth: 10, halign: 'center' }, // Qty
      4: { cellWidth: 25 }, // Item
      5: { cellWidth: 30 }, // Client
      6: { cellWidth: 18 }, // Status
      7: { cellWidth: 22 }, // Expiry
      8: { cellWidth: 20, halign: 'right' }, // Amount
      9: { cellWidth: 20, halign: 'right' }, // GST
      10: { cellWidth: 20, halign: 'right' } // Total
    },
    headStyles: { fillColor: [52, 152, 219], textColor: 255 },
    margin: { left: 14, right: 14 },
    theme: 'grid',
    didDrawPage: (dataArg) => {
      const pos = dataArg.cursor.y + 10;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(44, 62, 80);
      doc.text(`Total Expenses: INR ${totalSum.toLocaleString()}`, 14, pos);
    }
  });

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("This expense report is system generated by Sorim Technologies", 14, doc.internal.pageSize.height - 10);

  doc.save("company-expenses.pdf");
};


  return (
    <div className="expense-container">
      <h2>Company Expenses</h2>
      <table className="expense-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Item</th>
            <th>Client</th>
            <th>Status</th>
            <th>Expiry Date</th>
            <th>Amount</th>
            <th>GST</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {expensesData.map((exp, index) => (
            <tr key={index}>
              <td>{exp.date}</td>
              <td>{exp.type}</td>
              <td>{exp.description}</td>
              <td>{exp.quantity}</td>
              <td>{exp.item}</td>
              <td>{exp.client}</td>
              <td>{exp.status}</td>
              <td>{exp.expiryDate}</td>
              <td>INR {exp.amount.toLocaleString()}</td>
              <td>INR {exp.gst.toLocaleString()}</td>
              <td>INR {exp.total.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <button className="pdf-btn" onClick={exportPDF}>Export PDF</button>
    </div>
  );
};

export default CompanyExpenses;