 import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import "./Recordtable.css";
import logo from '../../assets/ofiiceLogo.webp';
 import { FaDownload, FaEdit, FaTrash } from "react-icons/fa";

 const Recordtable = () => {
  const [data, setData] = useState([
    { id: "ST001", name: "Aakash P", designation: "Software Engineer", salary: "10,000" },
    { id: "ST002", name: "Afzal Rahman K", designation: "Software Engineer", salary: "10,000" },
    { id: "ST003", name: "Gayathri V", designation: "Software Engineer", salary: "10,000" },
    { id: "ST004", name: "Gnanarathinam C", designation: "Software Engineer", salary: "10,000" },
    { id: "ST005", name: "Hareesh Padmanabhan V", designation: "Software Engineer", salary: "10,000" },
    { id: "ST006", name: "Hari Babu E", designation: "Software Engineer", salary: "10,000" },
    { id: "ST007", name: "Kaviarasi A", designation: "Software Engineer", salary: "10,000" },
    { id: "ST008", name: "Ponnuchamy V", designation: "Software Engineer", salary: "10,000" },
    { id: "ST009", name: "Tamilselvan S", designation: "Software Engineer", salary: "10,000" },
  ]);

  const [showModal, setShowModal] = useState(false);
  const [newRecord, setNewRecord] = useState({
    id: "",
    name: "",
    designation: "",
    salary: "",
  });

  const [isEditing, setIsEditing] = useState(false);
  const [editIndex, setEditIndex] = useState(null);

  const addCompanyHeader = (doc) => {
    const logoWidth = 40;
    const logoHeight = 20;
    const logoX = 14;
    const logoY = 10;

    doc.addImage(logo, 'PNG', logoX, logoY, logoWidth, logoHeight);

    const textX = logoX + logoWidth + 10;
    const textYStart = logoY + 5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("SORIM TECHNOLOGIES", textX, textYStart);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("4, Velayutham St, Puzhuthivakkam,", textX, textYStart + 7);
    doc.text("Madipakkam, Chennai, Tamil Nadu 600091", textX, textYStart + 12);
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    addCompanyHeader(doc);

    const currentDate = new Date();
    const formattedDate = currentDate.toLocaleDateString();
    const day = currentDate.toLocaleDateString(undefined, { weekday: 'long' });

    const totalSalary = data.reduce((sum, emp) => {
      const salary = parseFloat(emp.salary.replace(/,/g, '')) || 0;
      return sum + salary;
    }, 0);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Employee Salary Summary", 105, 45, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Date: ${formattedDate}`, 14, 55);
    doc.text(`Day: ${day}`, 150, 55);

    autoTable(doc, {
      startY: 65,
      head: [["Employee ID", "Name", "Designation", "Salary (INR)"]],
      body: data.map(emp => [emp.id, emp.name, emp.designation, emp.salary]),
      styles: { fontSize: 10 },
      headStyles: { fillColor: [22, 160, 133] },
      margin: { left: 14, right: 14 },
      theme: 'grid',
      didDrawPage: (dataArg) => {
        const pos = dataArg.cursor.y + 10;
        doc.setFont("helvetica", "bold");
        doc.setTextColor(44, 62, 80);
        doc.text(`Total Salary: INR ${totalSalary.toLocaleString()}`, 14, pos);
      }
    });

    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("This salary summary is system generated by Sorim Technologies", 14, doc.internal.pageSize.height - 10);

    doc.save("employee-salary-summary.pdf");
  };

  const exportSingleEmployeePDF = (employee) => {
    const doc = new jsPDF();
    addCompanyHeader(doc);

    const now = new Date();
    const formattedDate = now.toLocaleDateString();
    const monthYear = now.toLocaleString('default', { month: 'long', year: 'numeric' });

    const monthlyCTC = parseFloat(employee.salary.replace(/,/g, ''));
    const yearlyCTC = monthlyCTC * 12;

    const basic = monthlyCTC * 0.4;
    const hra = basic * 0.5;
    const conveyance = 1000;
    const splAllowance = monthlyCTC - (basic + hra + conveyance);

    const pf = basic * 0.12;
    let pt = 0;
    if (monthlyCTC > 60000) pt = 208;
    else if (monthlyCTC > 45000) pt = 171;
    else if (monthlyCTC > 30000) pt = 135;
    else if (monthlyCTC > 21000) pt = 100;

    const estimatedTaxBasedOnSlab = (yearlyCTC - 300000) * 0.05;
    const incomeTax = yearlyCTC <= 300000 ? 0 : estimatedTaxBasedOnSlab;
    const totalDeduction = pf + pt + incomeTax;
    const netPay = monthlyCTC - totalDeduction;

    const gratuity = (basic * 0.0481) * 12;
    const healthInsurance = 5000;

    doc.setFontSize(10);
    doc.text(`Payslip for: ${monthYear}`, 14, 45);
    doc.text(`Generated on: ${formattedDate}`, 150, 45);

    autoTable(doc, {
      startY: 55,
      head: [["Employee Details", ""]],
      body: [
        ["Employee ID", employee.id],
        ["Name", employee.name],
        ["Designation", employee.designation],
        ["Monthly CTC", `INR ${monthlyCTC.toFixed(2)}`],
        ["Yearly CTC", `INR ${yearlyCTC.toFixed(2)}`],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [22, 160, 133] },
      margin: { left: 14, right: 14 },
      theme: 'grid'
    });

    autoTable(doc, {
      startY: 105,
      head: [["Earnings", "Amount (INR)"]],
      body: [
        ["Basic", basic.toFixed(2)],
        ["HRA", hra.toFixed(2)],
        ["Conveyance", conveyance.toFixed(2)],
        ["Special Allowance", splAllowance.toFixed(2)],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [39, 174, 96] },
      margin: { left: 14, right: 110 },
      theme: 'grid'
    });

    autoTable(doc, {
      startY: 105,
      head: [["Deductions", "Amount (INR)"]],
      body: [
        ["PF", pf.toFixed(2)],
        ["PT", pt.toFixed(2)],
        ["Income Tax", incomeTax.toFixed(2)],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [231, 76, 60] },
      margin: { left: 110, right: 14 },
      theme: 'grid'
    });

    autoTable(doc, {
      startY: 165,
      head: [["Summary", "Amount"]],
      body: [
        ["Net Pay", `INR ${netPay.toFixed(2)}`],
        ["Gratuity (Yearly)", `INR ${gratuity.toFixed(2)}`],
        ["Health Insurance (Yearly)", `INR ${healthInsurance.toFixed(2)}`],
      ],
      styles: { fontSize: 10, fontStyle: 'bold' },
      headStyles: { fillColor: [52, 152, 219] },
      margin: { left: 14, right: 14 },
      theme: 'grid'
    });

    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("This payslip is system generated by Sorim Technologies", 14, doc.internal.pageSize.height - 10);

    doc.save(`${employee.name}_Payslip_${monthYear}.pdf`);
  };

  const handleInputChange = (e) => {
    setNewRecord({ ...newRecord, [e.target.name]: e.target.value });
  };

  const handleAddRecord = () => {
    if (isEditing) {
      const updatedData = [...data];
      updatedData[editIndex] = newRecord;
      setData(updatedData);
    } else {
      setData([...data, newRecord]);
    }

    setNewRecord({ id: "", name: "", designation: "", salary: "" });
    setShowModal(false);
    setIsEditing(false);
    setEditIndex(null);
  };

  const handleEdit = (index) => {
    setNewRecord(data[index]);
    setEditIndex(index);
    setIsEditing(true);
    setShowModal(true);
  };

  const handleDelete = (index) => {
    const updatedData = data.filter((_, i) => i !== index);
    setData(updatedData);
  };

  return (
    <div className="earnings-table-container">
      <div className="header2">
        <h2>Monthly Earnings Breakdown</h2>
        <button className="add-btn" onClick={() => {
          setShowModal(true);
          setIsEditing(false);
          setNewRecord({ id: "", name: "", designation: "", salary: "" });
        }}>Add</button>
      </div>

      <table className="earnings-table">
        <thead>
          <tr>
            <th>Employee ID</th>
            <th>Name</th>
            <th>Designation</th>
            <th>Salary</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {data.map((row, idx) => (
            <tr key={idx}>
              <td>{row.id}</td>
              <td>{row.name}</td>
              <td>{row.designation}</td>
              <td>{row.salary}</td>
              <td>
                <div className="icon-btns">
                  <div className="tooltip-container">
                    <button className="icon-btn download" onClick={() => exportSingleEmployeePDF(row)}><FaDownload /></button>
                    <span className="tooltip">Download</span>
                  </div>
                  <div className="tooltip-container">
                    <button className="icon-btn edit" onClick={() => handleEdit(idx)}><FaEdit /></button>
                    <span className="tooltip">Edit</span>
                  </div>
                  <div className="tooltip-container">
                    <button className="icon-btn delete" onClick={() => handleDelete(idx)}><FaTrash /></button>
                    <span className="tooltip">Delete</span>
                  </div>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <button className="pdf-btn" onClick={exportPDF}>Export PDF</button>

      {showModal && (
        <div className="modal-overlay">
          <div className="modal">
            <h3>{isEditing ? "Edit Employee" : "Add New Employee"}</h3>
            <input type="text" name="id" placeholder="Employee ID" value={newRecord.id} onChange={handleInputChange} />
            <input type="text" name="name" placeholder="Name" value={newRecord.name} onChange={handleInputChange} />
            <input type="text" name="designation" placeholder="Designation" value={newRecord.designation} onChange={handleInputChange} />
            <input type="text" name="salary" placeholder="Salary" value={newRecord.salary} onChange={handleInputChange} />
            <div className="modal-buttons">
              <button onClick={handleAddRecord}>{isEditing ? "Update" : "Add"}</button>
              <button onClick={() => {
                setShowModal(false);
                setIsEditing(false);
                setEditIndex(null);
              }}>Cancel</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Recordtable;